{
  "PackageNotSupported": " 3D-Paketgenerator wird noch nicht unterstützt.",
  "ModelComponentNotFound": "Ziel-3D-Modellkomponente nicht gefunden. Stellen Sie sicher, dass sie in der Konstruktion vorhanden ist.",
  "Upload": "Hochladen",
  "UploadOperationAborted": "Das Hochladen des generierten 3D-Modells in ein Fusion-Projekt dauert zu lange. Vorgang abgebrochen.",
  "FailedToUploadModel": "Fehler beim Hochladen des generierten 3D-Modells in das Fusion-Projekt.",
  "UploadedModel": "3D-Modell hochgeladen",
  "DesignNotFound": "Konstruktion wurde nicht gefunden oder ist ungültig.",
  "Save": "Speichern",
  "PackageGenerator": "Paket-Generator",
  "ModelGenerator": "Modell-Generator",
  "BodyHeight": "Körperhöhe",
  "BodyDiameter": "Körperdurchmesser",
  "PinPitch": "Pin-Abstand",
  "PinWidth": "Pin-Breite",
  "BoardThickness": "Leiterplattenstärke",
  "BodyOffset": "Körperversatz",
  "Span": "Spanne",
  "BodyWidth": "Körperbreite",
  "BodyLength": "Körperlänge",
  "Pitch": "Abstand",
  "TerminalWidth": "Klemmenbreite",
  "TerminalLand": "Klemmensteg",
  "ThermalPadLength": "Länge Wärmeleitpad",
  "ThermalPadWidth": "Breite Wärmeleitpad",
  "TerminalThickness": "Klemmenstärke",
  "DSidePins": "Pins Seite D",
  "ESidePins": "Pins Seite E",
  "PitchAlongD": "Abstand entlang D",
  "LeadSpan": "Leitungsspanne",
  "PitchAlongE": "Abstand entlang E",
  "TerminalTailLength": "Klemmenendlänge",
  "PinsAlongD": "Pins entlang D",
  "PinsAlongE": "Pins entlang E",
  "TerminalLength": "Klemmenlänge",
  "TerminalGap": "Klemmenlücke",
  "Pins": "Pins",
  "TabWidth": "Haltesteg-Breite",
  "TotalPins": "Pins gesamt",
  "EndTerminalWidth": "Endklemmenbreite",
  "BendRadius": "Biegeradius",
  "NormalTerminalWidth": "Breite lotrechte Klemme",
  "VerticalPinPitch": "vertikaler Pin-Abstand",
  "NormalTerminalLength": "Länge lotrechte Klemme",
  "HorizontalPinPitch": "horizontaler Pin-Abstand",
  "InnerThreadLength": "Innengewindelänge",
  "PostThreadLength": "Stiftgewindelänge",
  "LockDiameter": "Sperrdurchmesser",
  "LockHeight": "Sperrhöhe",
  "MountingHoleDiameter": "Durchmesser Montagebohrung",
  "HorizontalTerminalWidth": "Breite horizontale Klemme",
  "VerticalTerminalWidth": "Breite vertikale Klemme",
  "HorizontalTerminalLength": "Länge horizontale Klemme",
  "VerticalTerminalLength": "Länge vertikale Klemme",
  "TerminalPostLength": "Länge Anschlussstift",
  "TailLengthBelowRightAngleBody": "Endlänge unter rechtwinkligem Körper",
  "PartialThreadLength": "Teilgewindelänge",
  "NonThreadedHoleDiameter": "Bohrungsdurchmesser ohne Gewinde",
  "ESideSpan": "Spanne Seite E",
  "ESideWeldSpace": "Schweißbereich Seite E",
  "DSideSpan": "Spanne Seite D",
  "DSideWeldSpace": "Schweißbereich Seite D",
  "OddTerminalWidth": "Breite ungerade Klemme",
  "OddTerminalLength": "Länge ungerade Klemme",
  "PinLength": "Pin-Länge",
  "DPins": "D-Pins",
  "EPins": "E-Pins",
  "BandwidthRange": "Bandbreite",
  "BallDiameter": "Kugeldurchmesser",
  "HorizontalBallPitch": "Abstand horizontale Kugel",
  "VerticalBallPitch": "Abstand vertikale Kugel",
  "VerticalBalls": "vertikale Kugeln",
  "HorizontalBalls": "horizontale Kugeln",
  "TerminalSpan": "Klemmenspanne",
  "TerminalGapDistance": "Klemmenmitte - Achsabstand",
  "LeadDiameter": "Leitungsdurchmesser",
  "LeadThickness": "Leitungsstärke",
  "ChipHeight": "Chip-Höhe"
}