#include <CAM/CAMTypeDefs.h>
#include <CAM/CAM/CAM.h>
#include <CAM/CAM/CAMFolder.h>
#include <CAM/CAM/CAMFolders.h>
#include <CAM/CAM/CAMPattern.h>
#include <CAM/CAM/CAMPatterns.h>
#include <CAM/CAM/ChildOperationList.h>
#include <CAM/CAM/GenerateToolpathFuture.h>
#include <CAM/CAM/Machine.h>
#include <CAM/CAM/MachiningTime.h>
#include <CAM/CAM/PostProcessInput.h>
#include <CAM/CAM/Setup.h>
#include <CAM/CAM/Setups.h>
#include <CAM/Operations/CAMParameter.h>
#include <CAM/Operations/CAMParameters.h>
#include <CAM/Operations/Operation.h>
#include <CAM/Operations/OperationBase.h>
#include <CAM/Operations/Operations.h>
